[package]
name = "typst_geshihua"
version = "0.9.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "typst_geshihua"
path = "src/main.rs"

[lib]
name = "typst_geshihua"
path = "src/lib.rs"
crate-type = ["lib"]


[dependencies]
anyhow = "1.0.75"
clap = { version = "4.2.4", features = ["derive", "env"] }
itertools = "0.12.0"
once_cell = "1.18.0"
pretty = "0.12.3"
thiserror = "1.0.50"
typst-syntax = { git = "https://github.com/typst/typst.git", tag = "v0.9.0" }

[dev-dependencies]
insta = { version = "1.34.0", features = ["yaml"] }

[build-dependencies]
anyhow = "1.0.75"
vergen = { version = "8.2.5", features = [
  "build",
  "cargo",
  "git",
  "git2",
  "rustc",
] }

[profile.dev.package]
insta.opt-level = 3
similar.opt-level = 3
